# üîà Finally block

The block `finally` contains the statements to execute after the `try-catch` block.

**This block executes regardless of whether an exception is thrown.** Also, if an exception is thrown, the statements are executed even if there is no catch-block.

## Example 1

```js
async function getUsers()
{
    try {
        setLoading(true);
        const response = await fetch('https://reqres.in/api/users?page=2');
        // ... do something with the response
    } catch (error) {
        setError(true);
    } finally {
        setLoading(false);
    }
}
```

## Example 2

```js
openMyFile();

try {
    writeMyFile(theData);
} catch (error) {
    // handle error
} finally {
    // this is always executed
    closeMyFile();
}
```

## References

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

## ‚òïÔ∏è If you liked it, you can invite me for a coffee at:

https://www.buymeacoffee.com/latteandcode